### PR TITLE
Add Cucumber tests

### PR DESCRIPTION
**Pull request by Ordinateur-Hack**
Added Cucumber test for BDD

### CODE REVIEW

**Review by marcauberer — CHANGES_REQUESTED** [review]
@Ordinateur-Hack Please take care of implementing the execution of the cucumber tests in the GH Actions workflow. When I remember it correctly, we recently postponed that!

**Comment by Ordinateur-Hack** [comment]
@marcauberer Thanks for the reminder, Marc. Sadly, i still struggle with Maven not recognizing the Cucumber tests (e.g. using `mvn test` or `mvn clean install`). The result is always: `Tests run: 0, Failures: 0, Errors: 0, Skipped: 0`. I'll try to fix this problem within the next few days.

Note to myself:
- https://stackoverflow.com/questions/38454370/maven-not-running-cucumber-tests
- https://www.toolsqa.com/selenium-cucumber-framework/run-cucumber-test-from-command-line-terminal/
- https://stackoverflow.com/questions/56725004/how-to-run-cucumber-tests-with-mvn-test
- **https://stackoverflow.com/a/39735811/9655481**

**Comment by Ordinateur-Hack** [comment]
image

I've tried out every possible proposed solution (see [the links above](https://github.com/livepoll/live-poll-api/pull/32#issuecomment-753418004)) and still can't get it to work properly. I can run the cucumber tests perfectly fine in IntelliJ, but no tests are run using `mvn test` or `mvn clean install` (see the above screenshot). This is necessary since we want the CI workflow to run the cucumber tests, thus it has to work using `mvn test`.

[This](https://github.com/cucumber/cucumber-jvm/tree/main/spring) is the official Cucumber spring GitHub folder. We have our project configured exactly like that. The last thing I've tried is restructuring the `pom.xml` and trying to delete or replace some dependencies, but this seems pointless... **Any help appreciated**, maybe you can pull the code and try some things out. Run `mvn test -X` to see the full log (although this didn't reveal any useful information in my case).

**Review by marcauberer — APPROVED** [review]
I tried a bit around, but did not get it working either. I'd suggest to merge this for now and fix this issue later.

**Comment by Ordinateur-Hack** [comment]
Yeah, we can still try to incorporate this into GitHub Actions later on. For now, it's important that our feature files are in the repo, so I'll merge this.

**Pull request merged**
