### PR TITLE
Change volume file path relative to WSL2 (home)

### PR DESCRIPTION
**Pull request by Splines**
This is more performant instead of heaving the volumes NOT mounted in
WSL2.

### CODE REVIEW

**Comment by marcauberer** [comment]
@Splines why did you open this pr? This compose file is only for the CI workflow and not for local testing

**Comment by Splines** [comment]
@marcauberer Isn't this `docker-compose.yml` the file that holds all the information needed when executing `docker-compose up`? I didn't change the file in the workflow folder, but in the env folder.

**Comment by marcauberer** [comment]
@Splines ah okay, my bad. Then everything is alright

**Comment by Splines** [comment]
@marcauberer Can you approve then?

**Review by marcauberer — APPROVED** [review]

**Review by Niklas-23 — APPROVED** [review]

**Pull request merged**
